### PR TITLE
Update Naskh to Unicode 15 and more

### PR DESCRIPTION
**Pull request by khaledhosny**
This updates the Naskh font to fully cover all Arabic code points as of Unicode 15 (Arabic, Arabic Supplement, Arabic Extended-A, Arabic Extended-B, Arabic Extended-C, Arabic Presentation Forms-A, and Arabic Presentation Forms-B blocks), plus fixing a few other issues (some are already reported, others were found while reviewing the font).

This incorporates the changes in #195, so should be merged instead of it, or rebased after #195 is merged.

### CODE REVIEW

**Comment by simoncozens** [comment]
Good changes:

* Medial hehdo has changed (#189)
* Thousands and decimal separator (see #11)
* Gaf sarkash is a nicer length now!
* Serif digits
* Nice bismillah!
* Samvat redesign

Bad changes:

* lambar / lamdoublebar are broken in all forms
* U (U+0637) broken in all fonts
* U+06CD broken (tail anchoring missing)

Changes I don't understand

* Isolated heh (U+0647) now takes double-eye form?!
* U+0750 (ݐ) now has small dots?
* Proportional numerals - do we want this?

**Comment by khaledhosny** [comment]
> Bad changes:
> 
>   * lambar / lamdoublebar are broken in all forms
>   * U (U+0637) broken in all forms
>   * U+06CD broken (tail anchoring missing)

I can’t reproduce any of this. But it possible that you need a newer glyphsLib.

image

> Changes I don't understand
> 
>   * Isolated heh (U+0647) now takes double-eye form?!

Yes. So heh has a different form for final unconnected (the old isolated form) and really isolated (the new one). The single-eye form should only be used after another Arabic letter, and the double-eye is used otherwise (e.g. when heh is shown alone in alphabet charts, or after numbers for Hijri dates, in abbreviations, etc.). This is because the single-eye form looks very close to Arabic Indic 5.
image


>   * U+0750 (ݐ) now has small dots?

The old three dots were too wide, so in medial and initial forms they would clash with other neighboring letters. Here example word from its encoding proposal (https://www.unicode.org/L2/L2003/03168-african-chars.pdf)

image

>   * Proportional numerals - do we want this?

I changed the default numerals to be tabular (#196), and kept the old ones as proportional since we already have them.

**Comment by moyogo** [comment]
> > * Isolated heh (U+0647) now takes double-eye form?!
> 
> Yes. So heh has a different form for final unconnected (the old isolated form) and really isolated (the new one). The single-eye form should only be used after another Arabic letter, and the double-eye is used otherwise (e.g. when heh is shown alone in alphabet charts, or after numbers for Hijri dates, in abbreviations, etc.). This is because the single-eye form looks very close to Arabic Indic 5.

@khaledhosny Just out of curiosity: would the single-eye form but with crossing strokes work for this, would it be a good form to distinguish heh from Arabic Indic 5 in Naskh?

Screenshot 2023-09-08 at 16 17 20

**Comment by khaledhosny** [comment]
> > > * Isolated heh (U+0647) now takes double-eye form?!
> > 
> > 
> > Yes. So heh has a different form for final unconnected (the old isolated form) and really isolated (the new one). The single-eye form should only be used after another Arabic letter, and the double-eye is used otherwise (e.g. when heh is shown alone in alphabet charts, or after numbers for Hijri dates, in abbreviations, etc.). This is because the single-eye form looks very close to Arabic Indic 5.
> 
> @khaledhosny Just out of curiosity: would the single-eye form but with crossing strokes work for this, would it be a good form to distinguish heh from Arabic Indic 5 in Naskh?
> Screenshot 2023-09-08 at 16 17 20

Possibly, but using هـ is already the established way of doing this.

**Comment by khaledhosny** [comment]
Some examples of heh when not at the end of a word:
1694184097810-c9d3c622-6cbe-492f-8c35-167c7bb94423_
1694184218935-9888a309-09d4-4fb4-a0b7-c26c7f6f2f85_
1694184414331-082b24ad-9fd2-43d6-8314-65491aaaecbf_
1694184664889-75403499-6fa6-4482-b270-f72e7f46187f_

**Comment by simoncozens** [comment]
I'm now happy with this if you are. (I'm only asking since you're still adding commits...)

**Comment by khaledhosny** [comment]
I found and fixed a few small issues while working on the Kufi, but I think it is good to go now.

**Pull request merged**
